sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-stable-trusty
    packages:
      # - virtualbox
      # - vagrant
      - chefdk

branch: master
service: docker

before_script:
  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - cookstyle

script: rspec . && kitchen verify
