sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-stable-trusty
    packages:
      - chefdk
      - vagrant

branch: master

before_script:
  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - cookstyle

script: kitchen verify
