sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-stable-trusty
    packages:
      - virtualbox
      - vagrant
      - chefdk

branch: master


before_script:
  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - cookstyle

script: kitchen verify
